import { tv } from 'tailwind-variants';

export const directionStyles = tv({
  variants: {
    base: {
      vertical: 'grid-flow-row',
      horizontal: 'grid-flow-col',
    },
    sm: {
      vertical: 'sm:grid-flow-row',
      horizontal: 'sm:grid-flow-col',
    },
    md: {
      vertical: 'md:grid-flow-row',
      horizontal: 'md:grid-flow-col',
    },
    lg: {
      vertical: 'lg:grid-flow-row',
      horizontal: 'lg:grid-flow-col',
    },
    xl: {
      vertical: 'xl:grid-flow-row',
      horizontal: 'xl:grid-flow-col',
    },
    '2xl': {
      vertical: '2xl:grid-flow-row',
      horizontal: '2xl:grid-flow-col',
    },
  },
  defaultVariants: {
    base: 'vertical',
  },
});

export const columnStyles = tv({
  variants: {
    base: {
      '1': 'grid-cols-1',
      '2': 'grid-cols-2',
      '3': 'grid-cols-3',
      '4': 'grid-cols-4',
      '5': 'grid-cols-5',
      '6': 'grid-cols-6',
      '7': 'grid-cols-7',
      '8': 'grid-cols-8',
      '9': 'grid-cols-9',
      '10': 'grid-cols-10',
      '11': 'grid-cols-11',
      '12': 'grid-cols-12',
    },
    sm: {
      '1': 'sm:grid-cols-1',
      '2': 'sm:grid-cols-2',
      '3': 'sm:grid-cols-3',
      '4': 'sm:grid-cols-4',
      '5': 'sm:grid-cols-5',
      '6': 'sm:grid-cols-6',
      '7': 'sm:grid-cols-7',
      '8': 'sm:grid-cols-8',
      '9': 'sm:grid-cols-9',
      '10': 'sm:grid-cols-10',
      '11': 'sm:grid-cols-11',
      '12': 'sm:grid-cols-12',
    },
    md: {
      '1': 'md:grid-cols-1',
      '2': 'md:grid-cols-2',
      '3': 'md:grid-cols-3',
      '4': 'md:grid-cols-4',
      '5': 'md:grid-cols-5',
      '6': 'md:grid-cols-6',
      '7': 'md:grid-cols-7',
      '8': 'md:grid-cols-8',
      '9': 'md:grid-cols-9',
      '10': 'md:grid-cols-10',
      '11': 'md:grid-cols-11',
      '12': 'md:grid-cols-12',
    },
    lg: {
      '1': 'lg:grid-cols-1',
      '2': 'lg:grid-cols-2',
      '3': 'lg:grid-cols-3',
      '4': 'lg:grid-cols-4',
      '5': 'lg:grid-cols-5',
      '6': 'lg:grid-cols-6',
      '7': 'lg:grid-cols-7',
      '8': 'lg:grid-cols-8',
      '9': 'lg:grid-cols-9',
      '10': 'lg:grid-cols-10',
      '11': 'lg:grid-cols-11',
      '12': 'lg:grid-cols-12',
    },
    xl: {
      '1': 'xl:grid-cols-1',
      '2': 'xl:grid-cols-2',
      '3': 'xl:grid-cols-3',
      '4': 'xl:grid-cols-4',
      '5': 'xl:grid-cols-5',
      '6': 'xl:grid-cols-6',
      '7': 'xl:grid-cols-7',
      '8': 'xl:grid-cols-8',
      '9': 'xl:grid-cols-9',
      '10': 'xl:grid-cols-10',
      '11': 'xl:grid-cols-11',
      '12': 'xl:grid-cols-12',
    },
    '2xl': {
      '1': '2xl:grid-cols-1',
      '2': '2xl:grid-cols-2',
      '3': '2xl:grid-cols-3',
      '4': '2xl:grid-cols-4',
      '5': '2xl:grid-cols-5',
      '6': '2xl:grid-cols-6',
      '7': '2xl:grid-cols-7',
      '8': '2xl:grid-cols-8',
      '9': '2xl:grid-cols-9',
      '10': '2xl:grid-cols-10',
      '11': '2xl:grid-cols-11',
      '12': '2xl:grid-cols-12',
    },
  },
  defaultVariants: {
    base: '1',
  },
});

export const rowStyles = tv({
  variants: {
    base: {
      '1': 'grid-rows-1',
      '2': 'grid-rows-2',
      '3': 'grid-rows-3',
      '4': 'grid-rows-4',
      '5': 'grid-rows-5',
      '6': 'grid-rows-6',
      '7': 'grid-rows-7',
      '8': 'grid-rows-8',
      '9': 'grid-rows-9',
      '10': 'grid-rows-10',
      '11': 'grid-rows-11',
      '12': 'grid-rows-12',
    },
    sm: {
      '1': 'sm:grid-rows-1',
      '2': 'sm:grid-rows-2',
      '3': 'sm:grid-rows-3',
      '4': 'sm:grid-rows-4',
      '5': 'sm:grid-rows-5',
      '6': 'sm:grid-rows-6',
      '7': 'sm:grid-rows-7',
      '8': 'sm:grid-rows-8',
      '9': 'sm:grid-rows-9',
      '10': 'sm:grid-rows-10',
      '11': 'sm:grid-rows-11',
      '12': 'sm:grid-rows-12',
    },
    md: {
      '1': 'md:grid-rows-1',
      '2': 'md:grid-rows-2',
      '3': 'md:grid-rows-3',
      '4': 'md:grid-rows-4',
      '5': 'md:grid-rows-5',
      '6': 'md:grid-rows-6',
      '7': 'md:grid-rows-7',
      '8': 'md:grid-rows-8',
      '9': 'md:grid-rows-9',
      '10': 'md:grid-rows-10',
      '11': 'md:grid-rows-11',
      '12': 'md:grid-rows-12',
    },
    lg: {
      '1': 'lg:grid-rows-1',
      '2': 'lg:grid-rows-2',
      '3': 'lg:grid-rows-3',
      '4': 'lg:grid-rows-4',
      '5': 'lg:grid-rows-5',
      '6': 'lg:grid-rows-6',
      '7': 'lg:grid-rows-7',
      '8': 'lg:grid-rows-8',
      '9': 'lg:grid-rows-9',
      '10': 'lg:grid-rows-10',
      '11': 'lg:grid-rows-11',
      '12': 'lg:grid-rows-12',
    },
    xl: {
      '1': 'xl:grid-rows-1',
      '2': 'xl:grid-rows-2',
      '3': 'xl:grid-rows-3',
      '4': 'xl:grid-rows-4',
      '5': 'xl:grid-rows-5',
      '6': 'xl:grid-rows-6',
      '7': 'xl:grid-rows-7',
      '8': 'xl:grid-rows-8',
      '9': 'xl:grid-rows-9',
      '10': 'xl:grid-rows-10',
      '11': 'xl:grid-rows-11',
      '12': 'xl:grid-rows-12',
    },
    '2xl': {
      '1': '2xl:grid-rows-1',
      '2': '2xl:grid-rows-2',
      '3': '2xl:grid-rows-3',
      '4': '2xl:grid-rows-4',
      '5': '2xl:grid-rows-5',
      '6': '2xl:grid-rows-6',
      '7': '2xl:grid-rows-7',
      '8': '2xl:grid-rows-8',
      '9': '2xl:grid-rows-9',
      '10': '2xl:grid-rows-10',
      '11': '2xl:grid-rows-11',
      '12': '2xl:grid-rows-12',
    },
  },
  defaultVariants: {
    base: '1',
  },
});

export const gapStyles = tv({
  variants: {
    base: {
      '0': 'gap-0',
      '1': 'gap-1',
      '2': 'gap-2',
      '4': 'gap-4',
      '6': 'gap-6',
      '8': 'gap-8',
    },
    sm: {
      '0': 'sm:gap-0',
      '1': 'sm:gap-1',
      '2': 'sm:gap-2',
      '4': 'sm:gap-4',
      '6': 'sm:gap-6',
      '8': 'sm:gap-8',
    },
    md: {
      '0': 'md:gap-0',
      '1': 'md:gap-1',
      '2': 'md:gap-2',
      '4': 'md:gap-4',
      '6': 'md:gap-6',
      '8': 'md:gap-8',
    },
    lg: {
      '0': 'lg:gap-0',
      '1': 'lg:gap-1',
      '2': 'lg:gap-2',
      '4': 'lg:gap-4',
      '6': 'lg:gap-6',
      '8': 'lg:gap-8',
    },
    xl: {
      '0': 'xl:gap-0',
      '1': 'xl:gap-1',
      '2': 'xl:gap-2',
      '4': 'xl:gap-4',
      '6': 'xl:gap-6',
      '8': 'xl:gap-8',
    },
    '2xl': {
      '0': '2xl:gap-0',
      '1': '2xl:gap-1',
      '2': '2xl:gap-2',
      '4': '2xl:gap-4',
      '6': '2xl:gap-6',
      '8': '2xl:gap-8',
    },
  },
  defaultVariants: {
    base: '0',
  },
});

export const justifyStyles = tv({
  variants: {
    base: {
      start: 'justify-items-start',
      center: 'justify-items-center',
      end: 'justify-items-end',
      between: 'justify-items-between',
      around: 'justify-items-around',
      evenly: 'justify-items-evenly',
    },
    sm: {
      start: 'sm:justify-items-start',
      center: 'sm:justify-items-center',
      end: 'sm:justify-items-end',
      between: 'sm:justify-items-between',
      around: 'sm:justify-items-around',
      evenly: 'sm:justify-items-evenly',
    },
    md: {
      start: 'md:justify-items-start',
      center: 'md:justify-items-center',
      end: 'md:justify-items-end',
      between: 'md:justify-items-between',
      around: 'md:justify-items-around',
      evenly: 'md:justify-items-evenly',
    },
    lg: {
      start: 'lg:justify-items-start',
      center: 'lg:justify-items-center',
      end: 'lg:justify-items-end',
      between: 'lg:justify-items-between',
      around: 'lg:justify-items-around',
      evenly: 'lg:justify-items-evenly',
    },
    xl: {
      start: 'xl:justify-items-start',
      center: 'xl:justify-items-center',
      end: 'xl:justify-items-end',
      between: 'xl:justify-items-between',
      around: 'xl:justify-items-around',
      evenly: 'xl:justify-items-evenly',
    },
    '2xl': {
      start: '2xl:justify-items-start',
      center: '2xl:justify-items-center',
      end: '2xl:justify-items-end',
      between: '2xl:justify-items-between',
      around: '2xl:justify-items-around',
      evenly: '2xl:justify-items-evenly',
    },
  },
  defaultVariants: {
    base: 'start',
  },
});

export const itemsStyles = tv({
  variants: {
    base: {
      start: 'items-start',
      center: 'items-center',
      end: 'items-end',
      stretch: 'items-stretch',
    },
    sm: {
      start: 'sm:items-start',
      center: 'sm:items-center',
      end: 'sm:items-end',
      stretch: 'sm:items-stretch',
    },
    md: {
      start: 'md:items-start',
      center: 'md:items-center',
      end: 'md:items-end',
      stretch: 'md:items-stretch',
    },
    lg: {
      start: 'lg:items-start',
      center: 'lg:items-center',
      end: 'lg:items-end',
      stretch: 'lg:items-stretch',
    },
    xl: {
      start: 'xl:items-start',
      center: 'xl:items-center',
      end: 'xl:items-end',
      stretch: 'xl:items-stretch',
    },
    '2xl': {
      start: '2xl:items-start',
      center: '2xl:items-center',
      end: '2xl:items-end',
      stretch: '2xl:items-stretch',
    },
  },
  defaultVariants: {
    base: 'stretch',
  },
});

export const minWStyles = tv({
  variants: {
    base: {
      '0': 'min-w-0',
      full: 'min-w-full',
      fit: 'min-w-fit',
      max: 'min-w-max',
      screen: 'min-w-screen',
    },
    sm: {
      '0': 'sm:min-w-0',
      full: 'sm:min-w-full',
      fit: 'sm:min-w-fit',
      max: 'sm:min-w-max',
      screen: 'sm:min-w-screen',
    },
    md: {
      '0': 'md:min-w-0',
      full: 'md:min-w-full',
      fit: 'md:min-w-fit',
      max: 'md:min-w-max',
      screen: 'md:min-w-screen',
    },
    lg: {
      '0': 'lg:min-w-0',
      full: 'lg:min-w-full',
      fit: 'lg:min-w-fit',
      max: 'lg:min-w-max',
      screen: 'lg:min-w-screen',
    },
    xl: {
      '0': 'xl:min-w-0',
      full: 'xl:min-w-full',
      fit: 'xl:min-w-fit',
      max: 'xl:min-w-max',
      screen: 'xl:min-w-screen',
    },
    '2xl': {
      '0': '2xl:min-w-0',
      full: '2xl:min-w-full',
      fit: '2xl:min-w-fit',
      max: '2xl:min-w-max',
      screen: '2xl:min-w-screen',
    },
  },
  defaultVariants: {
    base: '0',
  },
});

export const minHStyles = tv({
  variants: {
    base: {
      '0': 'min-h-0',
      full: 'min-h-full',
      fit: 'min-h-fit',
      max: 'min-h-max',
      screen: 'min-h-screen',
    },
    sm: {
      '0': 'sm:min-h-0',
      full: 'sm:min-h-full',
      fit: 'sm:min-h-fit',
      max: 'sm:min-h-max',
      screen: 'sm:min-h-screen',
    },
    md: {
      '0': 'md:min-h-0',
      full: 'md:min-h-full',
      fit: 'md:min-h-fit',
      max: 'md:min-h-max',
      screen: 'md:min-h-screen',
    },
    lg: {
      '0': 'lg:min-h-0',
      full: 'lg:min-h-full',
      fit: 'lg:min-h-fit',
      max: 'lg:min-h-max',
      screen: 'lg:min-h-screen',
    },
    xl: {
      '0': 'xl:min-h-0',
      full: 'xl:min-h-full',
      fit: 'xl:min-h-fit',
      max: 'xl:min-h-max',
      screen: 'xl:min-h-screen',
    },
    '2xl': {
      '0': '2xl:min-h-0',
      full: '2xl:min-h-full',
      fit: '2xl:min-h-fit',
      max: '2xl:min-h-max',
      screen: '2xl:min-h-screen',
    },
  },
  defaultVariants: {
    base: '0',
  },
});
